# Generated by Django 4.2.6 on 2023-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userreq_id_userreq_req_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('chckindate', models.DateField()),
                ('chckoutdate', models.DateField()),
                ('purpose', models.TextField()),
                ('roomtype', models.TextField()),
                ('noofrooms', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Userreq',
        ),
    ]
