# Generated by Django 4.2.6 on 2023-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomno',
            field=models.IntegerField(default=10),
        ),
    ]
