# Generated by Django 4.2.6 on 2023-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_room_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomno',
        ),
        migrations.AddField(
            model_name='room',
            name='numsofroom',
            field=models.IntegerField(default=5),
        ),
    ]
