# Generated by Django 4.2.6 on 2023-11-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userreq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreq',
            name='id',
        ),
        migrations.AddField(
            model_name='userreq',
            name='req_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
